
services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: mobml
      POSTGRES_PASSWORD: 2005
      POSTGRES_DB: saas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: